; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ZuluSCSIv1_0, ZuluSCSIv1_0_mini, ZuluSCSIv1_1_plus


[env]
build_flags =
    -DBUILD_ENV=$PIOENV

; ZuluSCSI V1.0 hardware platform with GD32F205 CPU.
[env:ZuluSCSIv1_0]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
board = genericGD32F205VC
board_build.mcu = gd32f205vct6
board_build.core = gd32
board_build.ldscript = lib/ZuluSCSI_platform_GD32F205/zuluscsi_gd32f205.ld
ldscript_bootloader = lib/ZuluSCSI_platform_GD32F205/zuluscsi_gd32f205_btldr.ld
framework = spl
lib_compat_mode = off
lib_ldf_mode = chain+
lib_deps =
    SdFat=https://github.com/rabbitholecomputing/SdFat#2.2.3-gpt-exfat
    minIni
    ZuluSCSI_platform_GD32F205
    SCSI2SD
    ZuluContainerFS=https://github.com/rabbitholecomputing/ZuluContainerFS.git
    CUEParser=https://github.com/rabbitholecomputing/CUEParser#v2026.03.13
    GD32F20x_usbfs_library
upload_protocol = stlink
platform_packages = platformio/toolchain-gccarmnoneeabi@1.100301.220327
    framework-spl-gd32@https://github.com/CommunityGD32Cores/gd32-pio-spl-package.git
debug_tool = stlink
extra_scripts = src/build_bootloader.py
debug_build_flags =
    -Os -Wall -Wno-sign-compare -ggdb -g3
build_flags =
    ${env.build_flags}
    -Os -Wall -Wno-sign-compare -ggdb -g3 -Isrc
    -DBUILD_ENV=$PIOENV
    -D__SYSTEM_CLOCK_120M_PLL_IRC8M=120000000
    -DSPI_DRIVER_SELECT=3
    -DSD_CHIP_SELECT_MODE=2
    -DENABLE_DEDICATED_SPI=1
    -DPIO_USBFS_DEVICE_CDC
    -DZULUSCSI_V1_0
    -DPLATFORM_MASS_STORAGE
    -DCONTAINER_IMAGE_SUPPORT
    -DSDFAT_NOARDUINO
    -DFILE_COPY_CONSTRUCTOR_SELECT=FILE_COPY_CONSTRUCTOR_PUBLIC

; ZuluSCSI V1.0 mini hardware platform with GD32F205 CPU.
[env:ZuluSCSIv1_0_mini]
extends = env:ZuluSCSIv1_0
build_flags =
    ${env.build_flags}
    -Os -Wall -Wno-sign-compare -ggdb -g3 -Isrc
    -D__SYSTEM_CLOCK_120M_PLL_IRC8M=120000000
    -DSPI_DRIVER_SELECT=3
    -DSD_CHIP_SELECT_MODE=2
    -DENABLE_DEDICATED_SPI=1
    -DPIO_USBFS_DEVICE_CDC
    -DZULUSCSI_V1_0
    -DZULUSCSI_V1_0_mini
    -DPLATFORM_MASS_STORAGE
    -DCONTAINER_IMAGE_SUPPORT
    -DSDFAT_NOARDUINO
    -DFILE_COPY_CONSTRUCTOR_SELECT=FILE_COPY_CONSTRUCTOR_PUBLIC
lib_deps =
    ${env:ZuluSCSIv1_0.lib_deps}
   
   ; ZuluSCSI V1.1+ hardware platforms, this support v1.1, v1.1 ODE, and vl.2
[env:ZuluSCSIv1_1_plus]
extends = env:ZuluSCSIv1_0
build_flags =
    ${env.build_flags}
    -Os -Wall -Wno-sign-compare -ggdb -g3 -Isrc
    -D__SYSTEM_CLOCK_120M_PLL_IRC8M=120000000
    -DSPI_DRIVER_SELECT=3
    -DSD_CHIP_SELECT_MODE=2
    -DENABLE_DEDICATED_SPI=1
    -DPIO_USBFS_DEVICE_CDC
    -DHAS_SDIO_CLASS
    -DENABLE_AUDIO_OUTPUT
    -DENABLE_AUDIO_OUTPUT_I2S
    -DZULUSCSI_V1_1_plus
    -DPLATFORM_MASS_STORAGE
    -DCONTAINER_IMAGE_SUPPORT
    -DSDFAT_NOARDUINO
    -DFILE_COPY_CONSTRUCTOR_SELECT=FILE_COPY_CONSTRUCTOR_PUBLIC
    -DLOGBUFSIZE=4096
lib_deps =
    ${env:ZuluSCSIv1_0.lib_deps}
