#if defined(CONTROL_BOARD)

#ifndef SCREENTYPE_H
#define SCREENTYPE_H

typedef enum
{
    SCREEN_NONE,
	SCREEN_SPLASH,
    SCREEN_MAIN,
    SCREEN_NOSD,
    SCREEN_INFO,
    SCREEN_BROWSE_TYPE,
    SCREEN_BROWSE,
    SCREEN_BROWSE_FLAT,
    MESSAGE_BOX,
    SCREEN_COPY,
    SCREEN_INITIATOR_MAIN
} SCREEN_TYPE;

#endif

#endif