# ZuluSCSI™ - Copyright (c) 2022-2025 Rabbit Hole Computing™
#
# ZuluSCSI™ firmware is licensed under the GPL version 3 or any later version.
#
# https://www.gnu.org/licenses/gpl-3.0.html
# ----
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Bakes the exact git commit and a real build timestamp into the firmware,
# independent of the compiler's __DATE__/__TIME__ macros. Those macros only
# refresh when the specific translation unit that uses them actually gets
# recompiled -- if a build cache serves a stale object for that file, the
# reported build time silently stays frozen even though "clean"
# dependency-checking (touch, mtime) says it should be current.
#
# Writes a generated header (src/ZuluSCSI_build_info_generated.h) rather than
# appending to env["CPPDEFINES"] -- an earlier version did that, but this
# script is listed in extra_scripts without a "pre:" prefix, so it runs after
# PlatformIO has already scheduled the normal compile commands, and the
# appended defines never reached the actual compiler invocation (confirmed:
# the script's own diagnostic prints showed the right values, but `strings`
# on the resulting firmware.bin showed only the __DATE__/__TIME__ fallback).
# Writing the header sidesteps that timing question entirely: as long as the
# file is on disk with new content before the compiler reads it -- true for
# any extra_scripts, pre or post, since they all run during SCons's Python
# setup phase, strictly before any compiler subprocess is invoked -- SCons's
# ordinary #include dependency tracking takes care of the rest.

import datetime
import os
import subprocess

Import("env")

_project_dir = env.subst("$PROJECT_DIR")
_header_path = os.path.join(_project_dir, "src", "ZuluSCSI_build_info_generated.h")
print("inject_build_info.py: PROJECT_DIR = %r" % _project_dir)


def _run(cmd):
    try:
        out = subprocess.check_output(
            cmd, cwd=_project_dir, stderr=subprocess.STDOUT
        )
        return out.decode("utf-8", "replace").strip()
    except Exception as e:
        print("inject_build_info.py: %r failed: %r" % (cmd, e))
        return ""


git_rev = _run(["git", "rev-parse", "--short", "HEAD"])
git_status = _run(["git", "status", "--porcelain"])
git_ident = (git_rev or "unknown") + ("-dirty" if git_rev and git_status else "")

# No spaces: a raw space in a #define value is an easy way to end up with an
# unterminated string literal if any step along the way re-tokenizes it.
build_timestamp = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

print("inject_build_info.py: git_ident=%s build_timestamp=%s -> %s" % (git_ident, build_timestamp, _header_path))

with open(_header_path, "w") as f:
    f.write("// Auto-generated by inject_build_info.py on every build. Do not edit.\n")
    f.write("#pragma once\n")
    f.write('#define ZULU_BUILD_GIT_REV "%s"\n' % git_ident)
    f.write('#define ZULU_BUILD_TIMESTAMP "%s"\n' % build_timestamp)
